cosajobs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobs.urls')),
    # registration urls
    path('register',include('register.urls')),
    # login app urls
    path('login',include('login.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from . import views

app_name ="job"
urlpatterns = [
    path('',views.index,name='index'),
    path('aboutjob/<int:job_id>',views.aboutJob,name="aboutjob")
]

login/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path('',views.login,name='login'),
    path('logout',views.logout,name="logout"),
]

register/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.register,name='register'),
]

jobs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    """This models the user profile"""
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    img=models.ImageField(upload_to='profile_pics',default='profile_pics/test.jpg')
    
    def __str__(self):
        return self.user.username
    
    
    
class Job(models.Model):
    
    """This models the job database"""
    posted_by=models.ForeignKey(User,on_delete=models.CASCADE)
    job_name=models.CharField(max_length=100)
    job_image = models.ImageField(upload_to='jobs_pictures',default='profile_pics/test.jpg')
    
    
    def __str__(self):
        return self.job_name
    
    
class Qualification(models.Model):
    """This models the qualifications for a particular job"""
    job =models.ForeignKey(Job,on_delete=models.CASCADE)
    jQual =models.TextField()
    
    def __str__(self):
        return self.jQual
    
class Description(models.Model):
    """This models the job description"""
    job = models.ForeignKey(Job,models.CASCADE)
    job_description =models.TextField()
    
    def __str__(self):
        return self.job_description
    

    
   
    

login/models.py
from django.db import models

# Create your models here.

register/models.py
from django.db import models

# Create your models here.

jobs/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . models import Job,Qualification,Description,Profile
from django.contrib.auth.models import User
# Create your views here.

def index(request):
    
    jobs = Job.objects.all()
    users = User.objects.all()
    qual =Qualification.objects.all()
    
    return render(request,'index.html',{'jobs':jobs,'user':users})


def aboutJob(request,job_id):
    """It gives a detailed instruction about a job instance"""
    current_job =Job.objects.get(id=job_id)
    
    
    return render(request,'aboutjob.html',{'job':current_job})

login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
# Create your views here.

def login(request):
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = auth.authenticate(username=username,password=password)
        
        if user is not None:
            auth.login(request,user)
            
            return redirect("/")
            print("Logged in successfully")
        
    else:
        return render(request,'login.html')
        
def logout(request):
    auth.logout(request)
    
    return redirect("/")
    
    

register/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from . import views
# Create your views here.

def register(request):
    
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password = request.POST['password']
        
        
        email = request.POST['email']
        
        user = User.objects.create_user(username=username,password=password,email=email,first_name=first_name,last_name=last_name)
        user.save()
        
        print("Data saved and user created successfully...")
        
        return redirect('login')
    
        
        
    else:
        
    
        return render(request,'register.html')
    
    

templates/aboutjob.html
{% extends 'base.html' %}

{% block content %}

<!--container for job details-->
<div class="job_details">

    <div class="job_profile"> 

        
        <div class="job_pic" >
            <!--specific for jobs picture-->
            <img src="{{job.job_image.url}}" alt="" class="aboutjob_jobimage inline">
            <h3 class="aboutjobs_inline">posted by {{job.posted_by.first_name}} {{job.posted_by.last_name}}</h3>
    
        </div>

        <div class="displaycontent">

            

            <div class="aboutjobs_jobdescription">
                <!--the name of the job-->
                <div class="aboutjobs_jobname">
                    <p>{{job.job_name}}</p>
    
                </div>

                <!-- the description for the job -->
                <div class="aboutjobs_jobdescription">

                    <h3 class="aboutjobs_description_header">description</h3>

                    <!-- display all job description -->
                    {% for desc in job.description_set.all %}

                        <li class="items">{{desc}}</li>

                    {% endfor %}

                </div>

                <!--job qualifications-->
                <div class="aboutjobs_jobqualification">

                    <h3 class="aboutjobs_description_header">qualifications</h3>

                    <!--display all job qualification-->
                    {% for q in job.qualification_set.all %}

                        <li class="items">{{q}}</li>

                    {% endfor %}
                </div>
            </div>

        </div>

        
    </div>


</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'test/test.css' %}">
    <link rel="stylesheet" href="{% static 'aboutjob.css' %}">
    <title>Document</title>
</head>
<body>
    <h2>JoBooK</h2>
    
    <hr>
    <!--design the jobs display-->
    

    <hr>
    {% block content %}

    {% endblock %}
    
</body>
</html>

templates/index.html
{% extends 'base.html'%}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   <!-- <link rel="stylesheet" href="{% static 'test/test.css' %}">-->
</head>
<body>
    


    {% block content %}

    <!--job display design-->
    {% for job in jobs  %}
    <div id="main">

        <!-- profile info div-->
        <div class="profile_info">
            <div id="profile_pic" class="same">
                <!-- the picture associated with the job-->
                <img src="{{job.job_image.url}}" alt="" class="profile_image">

            </div>
            <!--job name display-->
            <div id="username" class="same">
                <a href="{% url 'job:aboutjob' job.id %}" class="same" id="username">{{job.job_name}}</a>
                
            </div>
        </div>

        

        <div class="job">
            {% for desc in job.description_set.all %}

            <li>{{desc}}</li>

        {% endfor %}

        <hr>
        </div>
    </div>

    {% endfor %}

    {% endblock %}
    

    
    

   
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>This is a login page Collins</h3>
    <form action="login" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username">
        <input type="password" name="password" placeholder="password">
        <input type="submit" value="Login">
    </form>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>CODEMY</h3>
    <blockquote>
        Register to join this amazing economy building community
    </blockquote>
    <!-- Registration form-->
    <form action="#" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="First Name" name="first_name">
        <input type="text" placeholder="First Name" name="last_name">
        <input type="text" placeholder="Username" name="username">
        <input type="text" placeholder="Password" name="password">
        <input type="text" placeholder="Email" name="email">
        
        

        <input type="submit" value="Register">
    </form>
</body>
</html>